use rand::seq::SliceRandom;
use rand::Rng;
use serde_json::{json, Value};

use crate::entities::entities::{Gender, Language, StoryGenre, StoryType};

pub fn get_voices_google(gender: Gender, language: Language) -> String {
    let en_male = vec![
        "en-US-Studio-O",
        "en-US-Neural2-D",
        "en-US-Neural2-J",
        "en-IN-Standard-C",
        "en-IN-Wavenet-B",
        "en-US-Standard-J",
    ];

    let en_female = vec![
        "en-US-Standard-H",
        "en-US-Journey-O",
        "en-US-Journey-F",
        "en-US-Neural2-C",
        "en-US-Journey-D",
    ];

    let de_male = vec![
        "de-DE-Standard-E",
        "de-DE-Studio-B",
        "de-DE-Neural2-B",
        "de-DE-Polyglot-1",
    ];

    let de_female = vec!["de-DE-Standard-F", "de-DE-Studio-C", "de-DE-Neural2-F"];

    let voices = match language {
        Language::German(_) => match gender {
            Gender::Male(_) => &de_male,
            Gender::Female(_) => &de_female,
        },
        Language::English(_) => match gender {
            Gender::Male(_) => &en_male,
            Gender::Female(_) => &en_female,
        },
    };

    let mut rng = rand::thread_rng();
    voices.choose(&mut rng).unwrap().to_string()
}
pub fn get_genre() -> String {
    let genres = vec![
        StoryGenre::Funny(String::from("funny")),
        StoryGenre::Horrific(String::from("horrific")),
        StoryGenre::Sad(String::from("sad")),
        StoryGenre::Perverted(String::from("perverted")),
        StoryGenre::Crazy(String::from("crazy")),
    ];

    let mut rng = rand::thread_rng();
    let random_index = rng.gen_range(0..genres.len());

    // Get the random genre
    let genre = genres[random_index].clone();

    let selected_genre = match genre {
        StoryGenre::Funny(_) => String::from("funny"),
        StoryGenre::Horrific(_) => String::from("horrific"),
        StoryGenre::Sad(_) => String::from("sad"),
        StoryGenre::Perverted(_) => String::from("perverted"),
        StoryGenre::Crazy(_) => String::from("crazy"),
    };

    selected_genre
}

pub fn get_story_type() -> StoryType {
    let narrator = StoryType::Narrator(String::from("narrator"));
    let chat = StoryType::Chat(String::from("chat"));
    let call = StoryType::Call(String::from("call"));
    let comments = StoryType::Comments(String::from("comments"));
    let story_types = vec![chat];

    let mut rng = rand::thread_rng();
    let random_index = rng.gen_range(0..story_types.len());

    // Get the random story type
    let story_type = story_types[random_index].clone();

    // Match and return the corresponding string
    story_type
}

pub fn get_character() -> String {
    let characters = vec![
        "The Protagonist – The central character who initiates or is involved in the primary conflict.",
        "The Best Friend – A loyal and supportive friend who offers emotional support and advice.",
        "The Ex-Boyfriend/Girlfriend – A former romantic partner who may bring additional drama or tension.",
        "The Stepbrother/Stepsister – A sibling by marriage who adds complexity to the family dynamics.",
        "The Skeptic – A character who is doubtful or dismissive about the situation.",
        "The Mediator – Someone who tries to mediate or resolve conflicts.",
        "The Jokester – A light-hearted character who uses humor to cope with or deflect tension.",
        "The Overreactor – A character who tends to blow situations out of proportion.",
        "The Informant – A character who provides crucial information or updates about the situation.",
        "The Neutral Party – A character who stays neutral or avoids taking sides.",
        "The Newcomer – A new addition to the group who offers fresh insights or causes unexpected reactions.",
        "The Concerned Parent – A parental or guardian figure who is concerned about the situation.",
        "The Annoyed Colleague – A coworker or classmate who is frustrated by the disruption.",
        "The Enthusiastic Supporter – Someone who is extremely supportive or excited about the situation.",
        "The Gossip – A character who loves spreading rumors or discussing private matters.",
        "two best friends",
        "a cheating spouse and a suspicious partner",
        "an estranged parent and their child",
        "a stepmother and her resentful stepdaughter",
        "a manipulative coworker and their victim",
        "a toxic ex and their former partner",
        "a married couple and a mysterious third person",
        "a jealous sibling",
        "a secretive spouse and an inquisitive partner",
        "a neighbor with a dark secret",
        "a controlling boss and their employee",
        "a distrusting friend",
        "an overprotective parent",
        "a friend with unrequited love",
        "a distant relative with hidden motives",
        "a recently divorced individual and their ex-in-laws",
        "a stranger who knows too much",
        "a friend who betrayed trust",
        "a single parent and their rebellious teenager",
        "a landlord with something to hide",
        "a neighbor with ulterior motives",
        "a mysterious online friend",
        "a family friend with an inappropriate crush",
        "a child in a custody battle",
        "a couple adopting a child with a mysterious past",
        "a retiree uncovering a family secret",
        "a babysitter who knows too much",
        "a firefighter saving someone with a dark secret",
        "a best friend hiding their true feelings",
        "a sibling who discovered a parent's affair",
        "a roommate involved in illegal activities",
        "a tourist falling in love with a local",
        "a married couple struggling with infertility",
        "a dog walker discovering something strange",
        "a couple dealing with unexpected pregnancy",
        "a neighbor with a hidden agenda",
        "a teacher involved in a student's scandal",
        "a friend with a hidden addiction",
        "a couple dealing with infidelity",
        "a sibling rivalry",
        "a roommate with a dangerous secret",
        "a friend turned enemy",
        "a jilted lover",
        "a mentor with questionable intentions",
        "a group of friends with a shared secret",
        "a step-sibling with hidden resentment",
        "a family torn apart by a lie",
        "a recently discovered half-sibling",
        "a long-lost parent",
        "a married couple facing a scandal",
        "a child and their imaginary friend",
        "a couple and their meddling in-laws",
        "a neighbor involved in a crime",
        "a childhood friend who harbors resentment",
        "a betrayed business partner and their accomplice",
        "a new romantic partner and their skeptical ex",
        "a parent and their adult child with differing values",
        "a mentor and their ambitious apprentice",
        "a college roommate with a hidden agenda",
        "a wedding planner with a secret vendetta",
        "a former student seeking revenge on a teacher",
        "a celebrity and their obsessed fan",
        "a trusted neighbor who is secretly envious",
        "a recently reunited family member with a hidden agenda",
        "a long-time friend who suddenly becomes distant",
        "a childhood rival seeking retribution",
        "a charity organizer with questionable motives",
        "a close-knit group of colleagues with a hidden scandal",
        "a former partner seeking reconciliation with conditions",
        "a longtime caretaker with a hidden past",
        "a distant cousin with a personal vendetta",
        "a devoted employee discovering their boss's dark secret",
        "a local politician with a clandestine agenda",
        "a dedicated volunteer uncovering corruption within their organization",
        "a lawyer defending a guilty client",
        "a retired soldier facing old demons",
        "a detective uncovering a personal mystery",
        "a couple with an open relationship",
        "a young couple with a controversial age gap",
        "a landlord dealing with a troublesome tenant",
        "a shopkeeper and a regular customer with a secret",
        "a nurse discovering a family connection",
        "a child with a secret they can't share",
        "a local celebrity hiding a scandal",
        "a cheating partner and a vengeful ex",
        "a barista who overhears a dangerous conversation",
        "a street performer with a mysterious admirer",
        "a gardener discovering a hidden crime",
        "a tourist caught in a local conspiracy",
        "a coach with a controversial past",
        "a journalist uncovering a community scandal",
        "a scientist with a moral dilemma",
        "a musician with a hidden addiction",
        "a priest with a crisis of faith",
        "a fortune teller predicting a dark future",
        "a fisherman discovering a strange catch",
        "a classmate harboring jealousy",
        "a doctor with a difficult patient",
        "a family friend with an inappropriate crush",
    ];

    let mut rng = rand::thread_rng();
    let random_index = rng.gen_range(0..characters.len());

    let character = characters[random_index];

    character.to_string()
}

pub fn get_acquaintance() -> String {
    let acquaintances  = vec![
    "The Loyal Sidekick – A dependable friend who always has your back.",
    "The Party Animal – A friend who loves to socialize and often brings energy and excitement to gatherings.",
    "The Intellectual – A friend who is thoughtful and enjoys deep conversations and debates.",
    "The Adventurer – A friend who is always up for new experiences and thrills.",
    "The Caregiver – A friend who is empathetic and takes on a nurturing role in the group.",
    "a step-sibling with hidden resentment",
    "a family torn apart by a lie",
    "a recently discovered half-sibling",
    "a long-lost parent",
    "a married couple facing a scandal",
    "a child and their imaginary friend",
    "a couple and their meddling in-laws",
    "a neighbor involved in a crime",
    "a childhood friend who harbors resentment",
    "a betrayed business partner and their accomplice",
    "a new romantic partner and their skeptical ex",
    "a parent and their adult child with differing values",
    "a mentor and their ambitious apprentice",
    "a college roommate with a hidden agenda",
    "a wedding planner with a secret vendetta",
    "a former student seeking revenge on a teacher",
    "a celebrity and their obsessed fan",
    "a trusted neighbor who is secretly envious",
    "a recently reunited family member with a hidden agenda",
    "a family friend with an inappropriate crush",
    "a child in a custody battle",
    "a couple adopting a child with a mysterious past",
    "a retiree uncovering a family secret",
    "a babysitter who knows too much",
    "a firefighter saving someone with a dark secret",
    "a best friend hiding their true feelings",
    "a sibling who discovered a parent's affair",
    "a roommate involved in illegal activities",
    "a tourist falling in love with a local",
    "a married couple struggling with infertility",
    "a dog walker discovering something strange",
    "a couple dealing with unexpected pregnancy",
    "a neighbor with a hidden agenda",
    "a teacher involved in a student's scandal",
    "a friend with a hidden addiction",
    "a long-time friend who suddenly becomes distant",
    "a childhood rival seeking retribution",
    "a charity organizer with questionable motives",
    "The Comedian – A friend who uses humor to lighten the mood and make people laugh.",
    "The Ambitious – A friend with strong goals and determination, always striving for success.",
    "The Practical – A friend who is grounded and offers realistic solutions and advice.",
    "The Philosopher – A friend who enjoys discussing big ideas and pondering life’s big questions.",
    "The Spontaneous – A friend who enjoys making impulsive decisions and embracing the moment.",
    "The Social Butterfly – A friend who easily connects with everyone and thrives in social settings.",
    "The Supportive – A friend who provides encouragement and emotional support during tough times.",
    "The Fashionista – A friend who is always up-to-date with the latest trends and fashion.",
    "The DIY Enthusiast – A friend who loves taking on home projects and crafting.",
    "The Tech-Savvy – A friend who excels in all things digital and often helps others with tech issues.",
    "The Traveler – A friend who loves exploring new places and sharing their travel experiences.",
    "The Environmentalist – A friend who is passionate about sustainability and eco-friendly practices.",
    "The Historian – A friend with a deep interest in history and often shares interesting facts and stories.",
    ];

    let mut rng = rand::thread_rng();
    let random_index = rng.gen_range(0..acquaintances.len());

    let acquaintance = acquaintances[random_index];

    acquaintance.to_string()
}

pub fn get_friend() -> String {
    let friends = vec![
    "The Loyal Sidekick – A dependable friend who always has your back.",
    "a cheating partner and a vengeful ex",
    "a barista who overhears a dangerous conversation",
    "a street performer with a mysterious admirer",
    "a lawyer defending a guilty client",
    "a retired soldier facing old demons",
    "a detective uncovering a personal mystery",
    "a couple with an open relationship",
    "a young couple with a controversial age gap",
    "a landlord dealing with a troublesome tenant",
    "a shopkeeper and a regular customer with a secret",
    "a nurse discovering a family connection",
    "a child with a secret they can't share",
    "a local celebrity hiding a scandal",
    "a family friend with an inappropriate crush",
    "a child in a custody battle",
    "a couple adopting a child with a mysterious past",
    "a retiree uncovering a family secret",
    "a babysitter who knows too much",
    "a firefighter saving someone with a dark secret",
    "a best friend hiding their true feelings",
    "a sibling who discovered a parent's affair",
    "a roommate involved in illegal activities",
    "a tourist falling in love with a local",
    "a married couple struggling with infertility",
    "a dog walker discovering something strange",
    "a couple dealing with unexpected pregnancy",
    "a neighbor with a hidden agenda",
    "a teacher involved in a student's scandal",
    "a friend with a hidden addiction",
    "a cheating partner and a vengeful ex",
    "a barista who overhears a dangerous conversation",
    "a street performer with a mysterious admirer",
    "a gardener discovering a hidden crime",
    "a tourist caught in a local conspiracy",
    "a coach with a controversial past",
    "a journalist uncovering a community scandal",
    "a scientist with a moral dilemma",
    "a musician with a hidden addiction",
    "a priest with a crisis of faith",
    "a fortune teller predicting a dark future",
    "a fisherman discovering a strange catch",
    "a classmate harboring jealousy",
    "a doctor with a difficult patient",
    "a family friend with an inappropriate crush",
    "a classmate harboring jealousy",
    "a doctor with a difficult patient",
    "a family friend with an inappropriate crush",
    "a child in a custody battle",
    "a couple adopting a child with a mysterious past",
    "a retiree uncovering a family secret",
    "a babysitter who knows too much",
    "a firefighter saving someone with a dark secret",
    "a best friend hiding their true feelings",
    "a sibling who discovered a parent's affair",
    "a roommate involved in illegal activities",
    "a tourist falling in love with a local",
    "a married couple struggling with infertility",
    "a couple and their meddling in-laws",
    "a neighbor involved in a crime",
        "a childhood friend who harbors resentment",
        "a betrayed business partner and their accomplice",
        "a new romantic partner and their skeptical ex",
        "a parent and their adult child with differing values",
        "a mentor and their ambitious apprentice",
        "a college roommate with a hidden agenda",
        "a wedding planner with a secret vendetta",
        "a former student seeking revenge on a teacher",
        "a celebrity and their obsessed fan",
        "a trusted neighbor who is secretly envious",
        "a recently reunited family member with a hidden agenda",
        "a long-time friend who suddenly becomes distant",
        "The Traveler – A friend who loves exploring new places and sharing their travel experiences.",
        "a childhood rival seeking retribution",
        "a charity organizer with questionable motives",
        "The Tech-Savvy – A friend who excels in all things digital and often helps others with tech issues.",
        "a step-sibling with hidden resentment",
        "The Environmentalist – A friend who is passionate about sustainability and eco-friendly practices.",
        "The Historian – A friend with a deep interest in history and often shares interesting facts and stories.",
        ];

    let mut rng = rand::thread_rng();
    let random_index = rng.gen_range(0..friends.len());

    let friend = friends[random_index];

    friend.to_string()
}

pub fn get_topic() -> String {
    // Define the topics for each genre
    let topics = vec![
        "Have you ever accidentally sent a text to the wrong person? What happened?",
        "What’s the silliest reason you’ve ever been late to something important?",
        "Describe a moment when you couldn’t stop laughing in a serious situation.",
        "Have you ever stumbled upon something that felt like it was from another world?",
        "What’s the most bizarre conspiracy theory you’ve ever heard?",
        "Have you ever had a dream that felt more real than reality?",
        "What’s the oddest gift you’ve ever received?",
        "Top 10 Animes 2024",
        "Animes",
        "What’s the most surreal conversation you’ve had with a stranger?",
        "Have you ever seen something so weird you couldn’t stop thinking about it?",
        "Cooking",
        "Hiking",
        "Why I am in love with my cousin",
        "Breaking Bad",
        "You are not the father of your child",
        "My Brother Turned Our Backyard Into a Farm... and Now We're Overrun with Chickens!",
        "My Friend Bought a Haunted House as a Joke... Now He's Missing!",
        "One Piece",
        "Naruto",
        "Hentai",
        "trash TV",
        "Ice Spice",
        "Guess my Gender",
        "I am not the father",
        "Eminem",
        "Politics",
        "My Girlfriend wasted all my money",
        "Knitting",
        "Fishing",
        "A wild Night",
        "Your theory on why more and more people are not wanting kids?",
        "Crazy homeless guy",
        "Science",
        "Rassism",
        "An old love",
        "Feminism",
        "Why all woman are trash",
        "toxic masculinity",
        "Annoying Neigbor",
        "Hot Doctor",
        "I left my wife for a younger woman",
        "Cheating",
        "Woman should be cheated on",
        "Woman cheat more often",
        "Feminism ruind society",
        "unfriendly cashier",
        "Jerry Springer",
        "dead beat dad",
        "narcissistic mother",
        "My wife spend all my cash and leaves me",
        "Reading",
        "Snoop Dogg is trash",
        "Donald Trump",
        "Trump fist fighting Biden",
        "Far left movement",
        "Kids are dumb",
        "top ten tik tok tips",
        "Should abortion be legal?",
        "Who’s the worst human you’ve ever met ?",
        "What’s the weirdest thing you’ve overheard in a public restroom?",
        "Should the U.S. become socialist?",
        "What’s your most embarrassing moment?",
        "Biden",
        "Describe a moment when you realized you knew too much about someone’s private life.",
        "What’s the most puzzling mystery you’ve ever encountered?",
        "Have you ever discovered something that made you question everything?",
        "Should animals be used for scientific or commercial testing?",
        "What’s the strangest coincidence you’ve noticed in your life?",
        "Describe a time when you found something that shouldn’t have been there.",
        "What’s the most intriguing secret someone’s ever shared with you?",
        "Have you ever witnessed something that made you rethink reality?",
        "Influencers negatively affect teenagers’ body image.",
        "What’s the most fascinating rumor you’ve heard that turned out to be true?",
        "Social Media: Is social media good for society?",
        "Which is better- TikTok or Instagram",
        "Have you ever found a hidden message or code in something unexpected?",
        "Russian hacking",
        "What’s the most perplexing question you’ve never found an answer to?",
        "Electric cars are overrated.",
        "Are socks with sandals a fashion faux pas or a bold statement?",
        "What’s the most unusual fact you’ve come across?",
        "Human cloning",
        "Should parents or other adults be able to ban books from schools and libraries?",
        "Fat people",
        "Fat gay people",
        "Fat models are stupid",
        "vaccination",
        "Mind Controll",
        "Flat Earth",
        "Racial profiling",
        "Fortnite is gay",
        "What’s the most curious encounter you’ve had with a stranger?",
        "Death Penalty: Should the death penalty be legal?",
        "Human trafficking",
        " Is cheerleading a sport?",
        "Have you ever uncovered a mystery that still haunts you?",
        " Should permitless, “constitutional carry” of guns be legal?",
        "Cyber bullying",
        "What’s a moment when you felt utterly defeated?",
        "Have you ever had to let go of a dream you deeply cherished?",
        "Describe a time when you felt like you failed someone you cared about.",
        "Have you ever had to make a choice that broke your heart?",
        " Is a college education worth it?",
        "What’s the saddest piece of news you’ve ever received?",
        "What’s the most difficult conversation you’ve ever had?",
        "Have you ever been in a situation where you felt there was no hope?",
        "What’s the most thought-provoking question you’ve ever been asked?",
        "What’s a fundamental question about religion or spirituality that you’ve wrestled with?",
        "How do different religious beliefs influence people's values and behaviors?",
        "What’s a religious or spiritual practice that you find intriguing?",
        "How have your views on religion or spirituality evolved over time?",
        "What’s the role of religion in addressing ethical or moral dilemmas?",
        "Being gay",
        "Transsexual people",
        "Mental Disorders like ADHD and Gender Identity Disorder",
        "What’s the most heartbreaking moment you’ve experienced?",
        "Describe a time when you had to cope with a significant loss.",
        "What’s the most difficult personal challenge you’ve faced?",
        "Women are naturally worse at math and science than men.",
        "All men are inherently aggressive and violent.",
        "Women are naturally worse at math and science than men.",
        "Mental health issues are just a result of weak character.",
        "People from certain ethnic backgrounds are less intelligent.",
        "The legal system is inherently biased in favor of women in divorce cases.",
        "Climate change is a hoax perpetuated for political gain.",
        "Vaccines are dangerous and cause more harm than good.",
        "All immigrants are taking jobs away from native citizens.",
        "Standardized testing is the best measure of student intelligence and ability.",
        "Mental illness is often exaggerated for attention or sympathy.",
        "Certain religious beliefs are inherently superior to others.",
        "Gun ownership should be unrestricted and unregulated.",
        "The education system is designed to suppress creativity and independent thinking.",
        "Certain forms of alternative medicine are just scams.",
        "Social media does more harm than good to society.",
        "The government is spying on its citizens under the guise of national security.",
        "Affirmative action is reverse discrimination and harms meritocracy.",
        "The media is biased and deliberately spreads misinformation.",
        "Homeless people are to blame for their own situation.",
        "LGBTQ+ rights are being pushed too aggressively and threaten traditional values.",
        "Have you ever had to say goodbye to someone you loved? How did you handle it?",
        "What’s the most poignant memory you have from a tough time in your life?",
        "Smoking",
        "That there exist no pay gap",
        "Farts",
        "gender equality",
        "Have you ever questioned your deepest desires in a way that left you unsettled, especially involving a stepbrother or stepsister?",
        "Describe a moment when you doubted your own morality, perhaps involving a stepbrother or stepsister.",
        "What’s the darkest realization you’ve had about human nature, especially when it comes to family dynamics with a step-sibling?",
        "Have you ever fantasized about something that made you reconsider your own ethics, particularly in a situation involving a stepbrother or stepsister?",
        "What’s the most twisted moral dilemma you’ve faced that made you question yourself, especially one involving a step-sibling?",
        "Have you ever had an experience that blurred the lines between pleasure and pain, particularly with a stepbrother or stepsister?",
        "What’s the most disturbing conversation you’ve had with yourself about your desires, especially those involving a step-sibling?",
        "What’s a perverse thought that has kept you up at night, particularly one involving a stepbrother or stepsister?",
        "Have you ever been drawn to an idea that felt dangerous or forbidden, especially in relation to a step-sibling?",
        "Have you ever had a fantasy that made you question your own boundaries, particularly with a stepbrother or stepsister?",
        "What’s the most unsettling dream you've had that blurred reality, especially involving a step-sibling?",
        "What’s the eeriest thing you’ve ever encountered that made you question your safety, particularly in relation to a stepbrother or stepsister?",
        "What’s the most taboo thought you’ve ever entertained about the nature of existence, particularly in relation to a step-sibling?",
        "Rock Climbing",
        "a small schlong",
        "That a small schlong is like a handicap",
        "Surfing",
        "a misunderstanding that tears apart a close relationship",
        "a financial crisis that forces tough decisions",
        "a sudden, unexpected move due to a hidden scandal",
        "a heroic rescue that has unintended consequences",
        "discovering a hidden talent that changes everything",
        "finding an old letter that reveals a shocking truth",
        "uncovering a family secret that could destroy everything",
        "an unexpected inheritance with a dark history",
        "being betrayed by a trusted friend at the worst possible moment",
        "revealing a surprise pregnancy that complicates everything",
        "getting caught in a lie that snowballs out of control",
        "meeting a celebrity who changes your life in unexpected ways",
        "a neighbor's bizarre behavior that hides a sinister truth",
        "winning an argument with a boss but losing something more important",
        "facing an embarrassing public moment that goes viral",
        "a chance encounter with an old crush that reignites old feelings",
        "finding a lost item of great value, but it belongs to someone dangerous",
        "being accused of something you didn’t do, leading to unexpected consequences",
        "receiving a mysterious message that changes your life",
        "all man are the same",
        "What’s the scariest thing you’ve ever found in an abandoned place?",
        "What’s the most frightening experience you’ve ever had?",
        "Describe a time when you felt truly terrified for your safety.",
        "What’s the creepiest thing you’ve ever encountered?",
        "What’s the most unsettling dream you’ve ever had?",
        "What’s the most disturbing experience you’ve had in a seemingly ordinary place?",
        "Have you ever had an encounter with a person who seemed like they were from another time?",
    ];

    // Randomly select a topic from the list
    let mut rng = rand::thread_rng();
    let random_index = rng.gen_range(0..topics.len());
    let random_topic = topics[random_index];

    random_topic.to_string()
}

pub fn get_peoples_involved() -> std::string::String {
    let peoples_involved_list = vec![
        "two best friends",
        "a cheating spouse and a suspicious partner",
        "an estranged parent and their child",
        "a stepmother and her resentful stepdaughter",
        "a manipulative coworker and their victim",
        "a toxic ex and their former partner",
        "a married couple and a mysterious third person",
        "a jealous sibling",
        "a secretive spouse and an inquisitive partner",
        "a neighbor with a dark secret",
        "a controlling boss and their employee",
        "a distrusting friend",
        "an overprotective parent",
        "a friend with unrequited love",
        "a distant relative with hidden motives",
        "a recently divorced individual and their ex-in-laws",
        "a stranger who knows too much",
        "a friend who betrayed trust",
        "a single parent and their rebellious teenager",
        "a landlord with something to hide",
        "a neighbor with ulterior motives",
        "a mysterious online friend",
        "a couple dealing with infidelity",
        "a sibling rivalry",
        "a roommate with a dangerous secret",
        "a friend turned enemy",
        "a jilted lover",
        "a mentor with questionable intentions",
        "a group of friends with a shared secret",
        "a step-sibling with hidden resentment",
        "a family torn apart by a lie",
        "a recently discovered half-sibling",
        "a long-lost parent",
        "a married couple facing a scandal",
        "a child and their imaginary friend",
        "a couple and their meddling in-laws",
        "a neighbor involved in a crime",
        "a single mother and her new partner",
        "an ex-partner seeking revenge",
        "a teenager with a double life",
        "a police officer and a suspect with a connection",
        "a teacher and their troubled student",
        "a celebrity caught in a scandal",
        "a mysterious traveler with a hidden past",
        "a widow dealing with a family secret",
        "a volunteer with a hidden agenda",
        "a lawyer defending a guilty client",
        "a retired soldier facing old demons",
        "a detective uncovering a personal mystery",
        "a couple with an open relationship",
        "a young couple with a controversial age gap",
        "a landlord dealing with a troublesome tenant",
        "a shopkeeper and a regular customer with a secret",
        "a nurse discovering a family connection",
        "a child with a secret they can't share",
        "a local celebrity hiding a scandal",
        "a cheating partner and a vengeful ex",
        "a barista who overhears a dangerous conversation",
        "a street performer with a mysterious admirer",
        "a gardener discovering a hidden crime",
        "a tourist caught in a local conspiracy",
        "a coach with a controversial past",
        "a journalist uncovering a community scandal",
        "a scientist with a moral dilemma",
        "a musician with a hidden addiction",
        "a priest with a crisis of faith",
        "a fortune teller predicting a dark future",
        "a fisherman discovering a strange catch",
        "a classmate harboring jealousy",
        "a doctor with a difficult patient",
        "a family friend with an inappropriate crush",
        "a child in a custody battle",
        "a couple adopting a child with a mysterious past",
        "a retiree uncovering a family secret",
        "a babysitter who knows too much",
        "a firefighter saving someone with a dark secret",
        "a best friend hiding their true feelings",
        "a sibling who discovered a parent's affair",
        "a roommate involved in illegal activities",
        "a tourist falling in love with a local",
        "Does anyone genuinely not like working?",
        "a married couple struggling with infertility",
        "a dog walker discovering something strange",
        "a couple dealing with unexpected pregnancy",
        "Do children who unalive/torture animals go to psychiatric facilities?",
        "I am scared of my wife and it low key turns me on",
        "guys who have a 100% SUCCESS RATE in getting girls, what is your secret?",
        "a neighbor with a hidden agenda",
        "a teacher involved in a student's scandal",
        "a friend with a hidden addiction",
    ];

    let mut rng = rand::thread_rng();
    let num = rng.gen_range(0..peoples_involved_list.len());

    return peoples_involved_list[num].to_string();
}

pub fn get_situations() -> std::string::String {
    let situations_list = vec![
            "a heated argument over a trivial matter that spirals out of control",
            "discovering a partner's infidelity through a misplaced text",
            "facing a life-or-death situation with an unlikely ally",
            "a surprise party that goes horribly wrong",
            "a family argument that reveals long-buried secrets",
            "winning the lottery but losing trust in everyone around you",
            "a secret love affair exposed in the most public way",
            "a job interview that turns into a moral dilemma",
            "unethic offer",
            "a romantic proposal that gets interrupted by an unexpected guest",
            "a missing pet that leads to an unexpected reunion",
            "a dramatic escape from a dangerous situation",
            "surviving a major accident that leaves you with a haunting memory",
            "a misunderstanding that tears apart a close relationship",
            "a financial crisis that forces tough decisions",
            "a sudden, unexpected move due to a hidden scandal",
            "a heroic rescue that has unintended consequences",
            "discovering a hidden talent that changes everything",
            "finding an old letter that reveals a shocking truth",
            "uncovering a family secret that could destroy everything",
            "an unexpected inheritance with a dark history",
            "being betrayed by a trusted friend at the worst possible moment",
            "revealing a surprise pregnancy that complicates everything",
            "getting caught in a lie that snowballs out of control",
            "meeting a celebrity who changes your life in unexpected ways",
            "a neighbor's bizarre behavior that hides a sinister truth",
            "winning an argument with a boss but losing something more important",
            "facing an embarrassing public moment that goes viral",
            "a chance encounter with an old crush that reignites old feelings",
            "finding a lost item of great value, but it belongs to someone dangerous",
            "being accused of something you didn’t do, leading to unexpected consequences",
            "receiving a mysterious message that changes your life",
            "all man are the same",
            "discovering a secret room in the house with a dark past",
            "being invited to a stranger's wedding and uncovering a family mystery",
            "getting an anonymous gift with hidden implications",
            "lost everything to man",
            "overhearing a conversation that changes everything you thought you knew",
            "finding a forgotten diary that reveals unsettling truths",
            "being mistaken for someone else, leading to a dangerous situation",
            "accidentally walking in on a private moment that leads to a scandal",
            "stumbling upon an explicit video that reveals someone's dark side",
            "discovering a secret adult club that leads to unexpected encounters",
            "encountering a stranger with a fetish that makes you question everything",
            "being invited to an exclusive party with hidden dangers",
            "being in jail",
            "finding out that your neighbor is involved in a secret underground scene",
            "meeting someone at a swingers club who holds the key to your past",
            "finding out that your crush is involved in something taboo",
            "uncovering a hidden world of forbidden desires in your own city",
            "a sudden urge to explore a hidden side of yourself",
            "experiencing a random act of kindness that leads to unexpected consequences",
            "getting stranded during a trip and discovering something new about yourself",
            "encountering an old nemesis with a shocking secret",
            "discovering a surprising connection with a new friend that complicates things",
            "facing a major dilemma at work that could ruin your career",
            "receiving unexpected advice from a mentor that changes your life",
            "stumbling upon an unusual hobby that leads to a new obsession",
            "dealing with a bizarre family tradition that causes tension",
            "confronting a difficult truth about yourself that you can't ignore",
            "loosing all money to ex wife",
            "a sudden change in plans that leads to an unexpected adventure",
            "receiving an unusual request that challenges your morals",
            "discovering an anonymous note with dangerous implications",
            "experiencing an unexplained event that defies logic",
            "how Stupid people can be",
            "unexpectedly meeting someone from the past who holds a grudge",
            "finding an item with unknown significance that leads to danger",
            "a strange coincidence that can’t be ignored, leading to a shocking discovery",
            "being offered a life-changing opportunity that comes with a catch",
            "witnessing a mysterious act that puts you in danger",
            "receiving an enigmatic message that draws you into a conspiracy",
            "finding a provocative letter that leads to an intense connection with unexpected consequences",
            "a heated argument that turns passionate but ends in betrayal",
            "an intimate conversation that escalates into a forbidden relationship",
            "a spontaneous kiss during a heated moment that reveals a hidden conflict",
            "discovering hidden desires in an old journal, but the journal belongs to someone you know",
            "an unexpected confession of feelings that leads to a surprising twist in your relationship",
            "a forbidden attraction with a colleague that leads to a dangerous situation",
            "an intense flirtation with a stranger that turns into a life-changing event",
            "a stolen glance that leads to a passionate kiss but results in unintended consequences",
            "an unexpected rendezvous that reveals hidden truths",
            "discovering a hidden attraction that complicates your life",
            "a chance encounter that sparks chemistry but ends in tragedy",
            "a secret admirer reveals themselves with shocking consequences",
            "finding a provocative letter that leads to a dark discovery",
            "a heated argument that turns into a scandalous affair",
            "an alluring surprise in a gift that leads to unexpected complications",
            "an intimate conversation that reveals a hidden agenda",
            "a spontaneous kiss that changes everything you thought you knew",
            "a mysterious invitation to a private event that uncovers a dark secret",
            "discovering hidden desires in an old journal that leads to dangerous consequences",
            "an unexpected confession of feelings that turns your world upside down",
            "a forbidden attraction with a colleague that threatens everything you've worked for",
            "an intense flirtation with a stranger that leads to a dangerous game",
            "A sudden server outage or technical glitch disrupts ongoing conversations and causes mass confusion and frustration among members.",
            "An unexpected surge of new members floods the server, overwhelming existing channels and sparking a chaotic adjustment period.",
            "A surprise announcement about a major server event or policy change catches everyone off guard, leading to a flurry of mixed reactions.",
            "A viral meme or internet trend takes over the server, with some members embracing it while others are irritated by the constant influx.",
            "A misunderstanding about the server rules or etiquette results in an escalating conflict, prompting heated debates and clarifications.",
    ];
    let mut rng = rand::thread_rng();
    let num = rng.gen_range(0..situations_list.len());
    return situations_list[num].to_string();
}
